version: '3.3'

services:
  db:
    image: postgres:15.0-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  backend:
    networks:
      - dvmn_7_network
    build: ../backend/
    container_name: backend
    restart: always
    volumes:
      - backend_static_data:/app/backend-static
      - media_data:/app/media
    depends_on:
      - db

  frontend:
    build: ../frontend/
    container_name: frontend
    volumes:
      - frontend_static_data:/app/frontend-static
    restart: always
    depends_on:
      - backend

volumes:
  db:
  backend_static_data:
  frontend_static_data:
  media_data:

networks:
  dvmn_7_network:
    external: true
