version: '3.3'

services:
  db:
    image: postgres:15.0-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  backend:
    build: ../backend/
    container_name: backend
    restart: always
    volumes:
      - backend_static_data:/app/backend-static
      - media_data:/app/media
    depends_on:
      - db

  frontend-nginx:
    build: ../frontend/
    container_name: frontend-nginx
    ports:
      - "80:80"
    volumes:
      - backend_static_data:/app/backend-static
      - media_data:/app/media
      - ../frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_static_data:/app/frontend-static
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on:
      - backend

volumes:
  db:
  backend_static_data:
  frontend_static_data:
  media_data:
