# Generated by Django 3.2.15 on 2023-04-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_product_name_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order_products', through='foodcartapp.OrderProduct', to='foodcartapp.Product', verbose_name='продукты'),
        ),
    ]
