# Generated by Django 3.2.15 on 2023-04-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_order_products'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_custome_f73a9a_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_phone',
            new_name='phonenumber',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['firstname', 'lastname'], name='foodcartapp_firstna_b9b5f7_idx'),
        ),
    ]
