# Generated by Django 3.2.15 on 2023-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230405_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('новый', 'новый'), ('подтверждение менеджером', 'подтверждение менеджером'), ('обработка рестораном', 'обработка рестораном'), ('доставка курьером', 'доставка курьером'), ('завершен', 'завершен')], default='новый', max_length=36),
        ),
    ]
