# Generated by Django 3.2.15 on 2023-04-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230405_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='назначенный ресторан'),
        ),
        migrations.CreateModel(
            name='OrderRestaurantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_prepare_order', models.BooleanField(default=False, verbose_name='может подготовить заказ')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='расстояние до ресторана')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_info', to='foodcartapp.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to='foodcartapp.restaurant')),
            ],
            options={
                'unique_together': {('order', 'restaurant')},
            },
        ),
    ]
