# Generated by Django 3.2.15 on 2023-04-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20230407_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('электронно', 'электронно'), ('наличными', 'наличными')], max_length=10, null=True, verbose_name='способ оплаты'),
        ),
    ]
