# Generated by Django 3.2.15 on 2023-04-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('электронно', 'электронно'), ('наличными', 'наличными')], default=None, max_length=10, verbose_name='способ оплаты'),
            preserve_default=False,
        ),
    ]
